config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :events do
  resources :attendees, :controller => 'event_attendees'
  resource :location, :controller => 'event_locations'
end


resources :events do
    collection do
        get :latest
    end
end

resources :events do
  collection do
  	    post :bulk_update
  end
end

resources :events do
    member do
        get :dashboard
    end
end

namespace :admin do
  resources :events
end

resources :events do
  member do
    post :join
    post :withdraw
  end
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
	belongs_to :event # 單數
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
	has_many :attendees # 複數
	belongs_to :category, :optional => true
	has_one :location # 單數
	has_many :event_groupships
    has_many :groups, :through => :event_groupships
end

app/models/event_groupship.rb
class EventGroupship < ApplicationRecord
	belongs_to :event
    belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :event_groupships
    has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :event # 單數
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

    before_action :authenticate
    layout "admin"

    # ....

    protected

    def authenticate
       authenticate_or_request_with_http_basic do |user_name, password|
           user_name == "username" && password == "password"
       end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
	before_action :find_event

def index
  @attendees = @event.attendees
end

def show
  @attendee = @event.attendees.find( params[:id] )
end

def new
  @attendee = @event.attendees.build
end

def create
  @attendee = @event.attendees.build( attendee_params )
  if @attendee.save
    redirect_to event_attendees_url( @event )
  else
    render :action => :new
  end
end

def edit
  @attendee = @event.attendees.find( params[:id] )
end

def update
  @attendee = @event.attendees.find( params[:id] )

  if @attendee.update( attendee_params )
    redirect_to event_attendees_url( @event )
  else
    render :action => :edit
  end

end

def destroy
  @attendee = @event.attendees.find( params[:id] )
  @attendee.destroy

  redirect_to event_attendees_url( @event )
end

protected

def find_event
  @event = Event.find( params[:event_id] )
end

def attendee_params
	params.require(:attendee).permit(:name)
end
end

app/controllers/event_locations_controller.rb
class EventLocationsController < ApplicationController
	before_action :find_event

  def show
    @location = @event.location
  end

  def new
    @location = @event.build_location
  end

  def create
    @location = @event.build_location( location_params )
    if @location.save
      redirect_to event_location_url( @event )
    else
      render :action => :new
    end
  end

  def edit
    @location = @event.location
  end

  def update
    @location = @event.location

    if @location.update( location_params )
      redirect_to event_location_url( @event )
    else
      render :action => :edit
    end

  end

  def destroy
    @location = @event.location
    @location.destroy

    redirect_to event_location_url( @event )
  end

  protected

  def find_event
    @event = Event.find( params[:event_id] )
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, :only => [ :show, :edit, :update, :destroy]
	def index
  if params[:keyword]
    @events = Event.where( [ "name like ?", "%#{params[:keyword]}%" ] )
  else
    @events = Event.all
  end

  @events = @events.page(params[:page]).per(5)
end

    def new
  @event = Event.new
end
    def create
  @event = Event.new(event_params)
  if @event.save
    redirect_to events_url
  else
    render :action => :new
  end
  flash[:notice] = "event was successfully created"
end
    def show
    @page_title = @event.name
end
    def edit
  
end
    def update
  if @event.update(event_params)
    redirect_to event_url(@event)
  else
    render :action => :edit
  end
  flash[:notice] = "event was successfully updated"
end
   def destroy
    @event.destroy

  redirect_to events_url
  flash[:alert] = "event was successfully deleted"
end
   def latest
  @events = Event.order("id DESC").limit(3)
end

def bulk_update
  ids = Array(params[:ids])
  events = ids.map{ |i| Event.find_by_id(i) }.compact

  if params[:commit] == "Publish"
    events.each{ |e| e.update( :status => "published" ) }
  elsif params[:commit] == "Delete"
    events.each{ |e| e.destroy }
  end

  redirect_to events_url
end

def dashboard
    @event = Event.find(params[:id])
end


private

    def event_params
  params.require(:event).permit(:name, :description, :category_id, :location_attributes => [:id, :name, :_destroy], :group_ids => [] )
end
    def set_event
  @event = Event.find(params[:id])
end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/event_locations_helper.rb
module EventLocationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def setup_event(event)
    event.build_location unless event.location
    event
end
end

app/views/event_attendees/edit.html.erb
<%= form_for @attendee, :url => event_attendee_path(@event, @attendee), :html => { :method => :patch } do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<ul>
<% @attendees.each do |attendee| %>
	<li>
	  <%= attendee.name %>
	  <%= link_to 'show', event_attendee_path(@event, attendee) %>
	  <%= link_to 'edit', edit_event_attendee_path(@event, attendee) %>
	  <%= link_to 'destroy', event_attendee_path(@event, attendee),
	                            :method => :delete %>
	</li>
<% end %>

</ul>

	  <%= link_to 'new attendee', new_event_attendee_path(@event) %>

app/views/event_attendees/new.html.erb
<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
   <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<p><%= @attendee.name %> </p>

app/views/event_locations/edit.html.erb
<%= form_for @location, :url => event_location_path(@event), :method => :patch do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_locations/new.html.erb
<%= form_for @location, :url => event_location_path(@event) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/event_locations/show.html.erb
<h1><%= @event.name %></h1>

<% if @event.location %>
  <p><%= @event.location.name %></p>
  <p><%= link_to "edit", edit_event_location_path(@event) %></p>
  <p><%= link_to "destroy", event_location_path(@event), :method => :delete %></p>
<% else %>
  <p>N/A</p>
  <p><%= link_to "Add location", new_event_location_path(@event) %></p>
<% end %>

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

<%= f.collection_select(:category_id, Category.all, :id, :name) %>

<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>

<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<%= f.fields_for :location do |location_form| %>
<p>
<%= location_form.label :name, "Location Name" %>
<%= location_form.text_field :name %>

<% p(location_form.public_instance_methods) %>


</p>
<% end %>

app/views/events/edit.html.erb
<%= form_for setup_event(@event), :url => event_path(@event), :method => :put do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<%= form_tag events_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>

<ul>
<% @events.each do |event| %>
  <li>
    <%= event.name %>
    <%= link_to "Show", event_path(event) %>
    <%= link_to 'Edit', edit_event_path(event) %>
    <%= link_to 'attendees', event_attendees_path(event) %>
    <%= link_to 'location', event_location_path(event) %>
    <%= button_to 'Delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
    <%= link_to 'Dashboard', dashboard_event_path(event) %>
  </li>
<% end %>
</ul>

<%= link_to 'New Event', new_event_path %>

<%= paginate @events %>

<%= form_tag bulk_update_events_path do %>

<ul>
  <% @events.each do |e| %>
    <li>
 	      <%= check_box_tag "ids[]", e.id, false %>
      <%= e.name %>
    </li>
  <% end %>
</ul>

<%= submit_tag "Delete" %>
<%= submit_tag "Publish" %>

<% end %>

app/views/events/new.html.erb
<%= form_for setup_event(@event), :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p>Category: <%= @event.category.try(:name) %></p>
<p>Group:
	<% @event.groups.each do |g| %>
		<%= g.name %>
	<% end %>
</p>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>
<%= yield %>

</body>
</html>